on:
  repository_dispatch:
    types: [run-cypress]

jobs:
  run-cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Cypress repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
